//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datiss.Budget.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datiss.Budget.Resources.EnumText", typeof(EnumText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاضلاب.
        /// </summary>
        public static string ActivityType_Waste {
            get {
                return ResourceManager.GetString("ActivityType_Waste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آب.
        /// </summary>
        public static string ActivityType_Water {
            get {
                return ResourceManager.GetString("ActivityType_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه جاری.
        /// </summary>
        public static string CofficientsGroup_CurrentCost {
            get {
                return ResourceManager.GetString("CofficientsGroup_CurrentCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد جاری.
        /// </summary>
        public static string CofficientsGroup_CurrentIncome {
            get {
                return ResourceManager.GetString("CofficientsGroup_CurrentIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه سرمایه ای.
        /// </summary>
        public static string CofficientsGroup_ForcastCost {
            get {
                return ResourceManager.GetString("CofficientsGroup_ForcastCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد سرمایه ای.
        /// </summary>
        public static string CofficientsGroup_ForcastIncome {
            get {
                return ResourceManager.GetString("CofficientsGroup_ForcastIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string EntityStatus_Deleted {
            get {
                return ResourceManager.GetString("EntityStatus_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string EntityStatus_Disabled {
            get {
                return ResourceManager.GetString("EntityStatus_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string EntityStatus_Enabled {
            get {
                return ResourceManager.GetString("EntityStatus_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string OrganizationType_City {
            get {
                return ResourceManager.GetString("OrganizationType_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهرستان.
        /// </summary>
        public static string OrganizationType_County {
            get {
                return ResourceManager.GetString("OrganizationType_County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string OrganizationType_Root {
            get {
                return ResourceManager.GetString("OrganizationType_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روستا.
        /// </summary>
        public static string OrganizationType_Village {
            get {
                return ResourceManager.GetString("OrganizationType_Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایه.
        /// </summary>
        public static string RecordType_Base {
            get {
                return ResourceManager.GetString("RecordType_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش بینی.
        /// </summary>
        public static string RecordType_Forcast {
            get {
                return ResourceManager.GetString("RecordType_Forcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string ReportParamType_City {
            get {
                return ResourceManager.GetString("ReportParamType_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولین ثابت.
        /// </summary>
        public static string ReportParamType_Constant {
            get {
                return ResourceManager.GetString("ReportParamType_Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دومین ثابت.
        /// </summary>
        public static string ReportParamType_Constant2 {
            get {
                return ResourceManager.GetString("ReportParamType_Constant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سومین ثابت.
        /// </summary>
        public static string ReportParamType_Constant3 {
            get {
                return ResourceManager.GetString("ReportParamType_Constant3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهرستان.
        /// </summary>
        public static string ReportParamType_County {
            get {
                return ResourceManager.GetString("ReportParamType_County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string ReportParamType_Date {
            get {
                return ResourceManager.GetString("ReportParamType_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد.
        /// </summary>
        public static string ReportParamType_Number {
            get {
                return ResourceManager.GetString("ReportParamType_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان.
        /// </summary>
        public static string ReportParamType_Organization {
            get {
                return ResourceManager.GetString("ReportParamType_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن.
        /// </summary>
        public static string ReportParamType_Text {
            get {
                return ResourceManager.GetString("ReportParamType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روستا.
        /// </summary>
        public static string ReportParamType_Village {
            get {
                return ResourceManager.GetString("ReportParamType_Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال مالی.
        /// </summary>
        public static string ReportParamType_Year {
            get {
                return ResourceManager.GetString("ReportParamType_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصارف وجوه.
        /// </summary>
        public static string TablesName_ConsumptionFunction {
            get {
                return ResourceManager.GetString("TablesName_ConsumptionFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه های جاری.
        /// </summary>
        public static string TablesName_CurrentCost {
            get {
                return ResourceManager.GetString("TablesName_CurrentCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمدهای جاری.
        /// </summary>
        public static string TablesName_CurrentIncome {
            get {
                return ResourceManager.GetString("TablesName_CurrentIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر هزینه ها جاری.
        /// </summary>
        public static string TablesName_OtherCurrentCost {
            get {
                return ResourceManager.GetString("TablesName_OtherCurrentCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منابع وجوه.
        /// </summary>
        public static string TablesName_ResourcesFunction {
            get {
                return ResourceManager.GetString("TablesName_ResourcesFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کلی فاضلاب.
        /// </summary>
        public static string TablesName_WsTotalBudget {
            get {
                return ResourceManager.GetString("TablesName_WsTotalBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کلی آب.
        /// </summary>
        public static string TablesName_WTotalBudget {
            get {
                return ResourceManager.GetString("TablesName_WTotalBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناخته نشده.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
