//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datiss.Budget.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datiss.Budget.Resources.ServiceMessages", typeof(ServiceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تکراری است..
        /// </summary>
        public static string DuplicateData {
            get {
                return ResourceManager.GetString("DuplicateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل ({0}) تکراری است..
        /// </summary>
        public static string DuplicateEmails {
            get {
                return ResourceManager.GetString("DuplicateEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان وارد شده تکراری است..
        /// </summary>
        public static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان ({0}) تکراری است..
        /// </summary>
        public static string DuplicateNames {
            get {
                return ResourceManager.GetString("DuplicateNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی شما برای تغییر اطلاعات سازمان وجود ندارد. خطا در سطر {0} فایل اکسل.
        /// </summary>
        public static string ImportExcelAccessError {
            get {
                return ResourceManager.GetString("ImportExcelAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده سطر {0} در اکسل مشکل دارد. لطفاً ورودی ها را بررسی نمایید..
        /// </summary>
        public static string ImportExcelLogicError {
            get {
                return ResourceManager.GetString("ImportExcelLogicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان به کد ({0}) در سیستم یافت نشد..
        /// </summary>
        public static string ImportExcelNotExistOrg {
            get {
                return ResourceManager.GetString("ImportExcelNotExistOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان های ({0}) در فایل شما اطلاعاتی ندارند. آیا مایل به ادامه هستید؟.
        /// </summary>
        public static string ImportExcelOrgNotInExcel {
            get {
                return ResourceManager.GetString("ImportExcelOrgNotInExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود اطلاعات با موفقیت انجام گردید..
        /// </summary>
        public static string ImportExcelSuccess {
            get {
                return ResourceManager.GetString("ImportExcelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات سال{0} برای شهر{1} قبلا ثبت شده است.
        /// </summary>
        public static string Logic_BranchFeeAmount {
            get {
                return ResourceManager.GetString("Logic_BranchFeeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری {0} و طبقه مصرف {1} قبلا ثبت شده است.
        /// </summary>
        public static string Logic_ConsumeForcast {
            get {
                return ResourceManager.GetString("Logic_ConsumeForcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری {0} قبلا ثبت شده است..
        /// </summary>
        public static string Logic_DWasteType {
            get {
                return ResourceManager.GetString("Logic_DWasteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری {0} قبلا ثبت شده است..
        /// </summary>
        public static string Logic_DWaterType {
            get {
                return ResourceManager.GetString("Logic_DWaterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری {0} و قطر لوله {1} قبلا ثبت شده است.
        /// </summary>
        public static string Logic_WasteSalesSplit {
            get {
                return ResourceManager.GetString("Logic_WasteSalesSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری {0} و قطر لوله {1} قبلا ثبت شده است.
        /// </summary>
        public static string Logic_WaterSalesSplit {
            get {
                return ResourceManager.GetString("Logic_WaterSalesSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل وجود داده وابسته امکان حذف نمی باشد..
        /// </summary>
        public static string RelationDataSoftDeleted {
            get {
                return ResourceManager.GetString("RelationDataSoftDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد..
        /// </summary>
        public static string Succeed {
            get {
                return ResourceManager.GetString("Succeed", resourceCulture);
            }
        }
    }
}
