//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datiss.Budget.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datiss.Budget.Resources.ServiceMessages", typeof(ServiceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تکراری است..
        /// </summary>
        public static string DuplicateData {
            get {
                return ResourceManager.GetString("DuplicateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل ({0}) تکراری است..
        /// </summary>
        public static string DuplicateEmails {
            get {
                return ResourceManager.GetString("DuplicateEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان وارد شده تکراری است..
        /// </summary>
        public static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان ({0}) تکراری است..
        /// </summary>
        public static string DuplicateNames {
            get {
                return ResourceManager.GetString("DuplicateNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازه سال مالی وارد شده تکراری است ..
        /// </summary>
        public static string FinanceYearCopyLength {
            get {
                return ResourceManager.GetString("FinanceYearCopyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال مالی وارد شده تکراری است ..
        /// </summary>
        public static string FinanceYearDuplicateYear {
            get {
                return ResourceManager.GetString("FinanceYearDuplicateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایان سال مالی نباید کوچکتر از شروع آن باشد ..
        /// </summary>
        public static string FinanceYearInvalidEndYear {
            get {
                return ResourceManager.GetString("FinanceYearInvalidEndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازه سال مالی وارد شده نامعتبر است ..
        /// </summary>
        public static string FinanceYearLengthYear {
            get {
                return ResourceManager.GetString("FinanceYearLengthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی شما برای وارد کردن اطلاعات سازمان وجود ندارد. [سطر {0} فایل اکسل].
        /// </summary>
        public static string ImportExcelAccessError {
            get {
                return ResourceManager.GetString("ImportExcelAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان انجام این عملیات به دلیل نبود رکورد در جدول وابسته، وجود ندارد..
        /// </summary>
        public static string ImportExcelCalculationField {
            get {
                return ResourceManager.GetString("ImportExcelCalculationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطر لوله های :&lt;br&gt;{0} برای &quot;{1}&quot; در فایل اکسل شما اطلاعاتی ندارند..
        /// </summary>
        public static string ImportExcelDiameterPipeOrgNotInExcel {
            get {
                return ResourceManager.GetString("ImportExcelDiameterPipeOrgNotInExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در فایل اکسل شما اطلاعات قطر لوله :&lt;br&gt;{0} برای کاربری &quot;{1}&quot; ، &quot;{2}&quot; وجود ندارد..
        /// </summary>
        public static string ImportExcelDiameterPipeUserTypeOrgNotInExcel {
            get {
                return ResourceManager.GetString("ImportExcelDiameterPipeUserTypeOrgNotInExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سطر {0} فایل اکسل، کد قطر لوله &quot;{1}&quot; معتبر نیست ..
        /// </summary>
        public static string ImportExcelInvalidDiameterPipe {
            get {
                return ResourceManager.GetString("ImportExcelInvalidDiameterPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سطر {0} فایل اکسل، کد سال &quot;{1}&quot; معتبر نیست ..
        /// </summary>
        public static string ImportExcelInvalidFinanceYear {
            get {
                return ResourceManager.GetString("ImportExcelInvalidFinanceYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سطر {0} فایل اکسل، کد &quot;{1}&quot; معتبر نیست ..
        /// </summary>
        public static string ImportExcelInvalidTitle {
            get {
                return ResourceManager.GetString("ImportExcelInvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سطر {0} فایل اکسل، کد طبقه مصرف&quot;{1}&quot; معتبر نیست ..
        /// </summary>
        public static string ImportExcelInvalidUsageLayer {
            get {
                return ResourceManager.GetString("ImportExcelInvalidUsageLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سطر {0} فایل اکسل، کد طبقه مصرف &quot;{1}&quot; برای کاربری &quot;{2}&quot; معتبر نیست ..
        /// </summary>
        public static string ImportExcelInvalidUsageLayerUserType {
            get {
                return ResourceManager.GetString("ImportExcelInvalidUsageLayerUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سطر {0} فایل اکسل، کد کاربری &quot;{1}&quot; معتبر نیست ..
        /// </summary>
        public static string ImportExcelInvalidUserType {
            get {
                return ResourceManager.GetString("ImportExcelInvalidUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده سطر {0} در اکسل مشکل دارد. لطفاً ورودی ها را بررسی نمایید..
        /// </summary>
        public static string ImportExcelLogicError {
            get {
                return ResourceManager.GetString("ImportExcelLogicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجاز به ورود اطلاعات برای &quot; {0} &quot; نیستید.[سطر {1} فایل اکسل].
        /// </summary>
        public static string ImportExcelNotAllowedOrg {
            get {
                return ResourceManager.GetString("ImportExcelNotAllowedOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سطر {0} فایل اکسل، کد سازمان &quot;{1}&quot; معتبر نیست ..
        /// </summary>
        public static string ImportExcelNotExistOrg {
            get {
                return ResourceManager.GetString("ImportExcelNotExistOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان های ({0}) در فایل اکسل شما اطلاعاتی ندارند. آیا مایل به ادامه هستید؟.
        /// </summary>
        public static string ImportExcelOrgNotInExcel {
            get {
                return ResourceManager.GetString("ImportExcelOrgNotInExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود اطلاعات با موفقیت انجام گردید..
        /// </summary>
        public static string ImportExcelSuccess {
            get {
                return ResourceManager.GetString("ImportExcelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان های :&lt;br&gt;{0} برای &quot;{1}&quot; در فایل اکسل شما اطلاعاتی ندارند..
        /// </summary>
        public static string ImportExcelTitleNotInExcel {
            get {
                return ResourceManager.GetString("ImportExcelTitleNotInExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در فایل اکسل شما اطلاعات طبقه مصرف :&lt;br&gt;{0} برای کاربری &quot;{1}&quot; ، &quot;{2}&quot; وجود ندارد..
        /// </summary>
        public static string ImportExcelUsageLayerUserTypeOrgNotInExcel {
            get {
                return ResourceManager.GetString("ImportExcelUsageLayerUserTypeOrgNotInExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری های :&lt;br&gt;{0} در فایل اکسل شما اطلاعاتی ندارند..
        /// </summary>
        public static string ImportExcelUserTypeNotInExcel {
            get {
                return ResourceManager.GetString("ImportExcelUserTypeNotInExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری های :&lt;br&gt;{0} برای &quot;{1}&quot; در فایل اکسل شما اطلاعاتی ندارند..
        /// </summary>
        public static string ImportExcelUserTypeOrgNotInExcel {
            get {
                return ResourceManager.GetString("ImportExcelUserTypeOrgNotInExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطاهای داده ای را بررسی کنید..
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات &quot;{1}&quot; برای فعالیت {0} قبلا ثبت شده است..
        /// </summary>
        public static string Logic_ActivityDuplicate {
            get {
                return ResourceManager.GetString("Logic_ActivityDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات قطر لوله {0} برای &quot;{1}&quot; قبلا ثبت شده است..
        /// </summary>
        public static string Logic_DiameterPipeOrgDuplicate {
            get {
                return ResourceManager.GetString("Logic_DiameterPipeOrgDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  این عملیات را برای سال غیر فعال نمی توانید انجام دهید..
        /// </summary>
        public static string Logic_InputDisableYearData {
            get {
                return ResourceManager.GetString("Logic_InputDisableYearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان &quot;{0}&quot; قبلا ثبت شده است ..
        /// </summary>
        public static string Logic_OrganizationDuplicate {
            get {
                return ResourceManager.GetString("Logic_OrganizationDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات {0} برای &quot;{1}&quot; قبلا ثبت شده است..
        /// </summary>
        public static string Logic_TitleDuplicate {
            get {
                return ResourceManager.GetString("Logic_TitleDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری {0} و قطر لوله {1} برای &quot;{2}&quot; قبلا ثبت شده است..
        /// </summary>
        public static string Logic_UserTypeDiameterPipeDuplicate {
            get {
                return ResourceManager.GetString("Logic_UserTypeDiameterPipeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری {0} برای &quot;{1}&quot; قبلا ثبت شده است..
        /// </summary>
        public static string Logic_UserTypeDuplicate {
            get {
                return ResourceManager.GetString("Logic_UserTypeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری {0} و طبقه مصرف {1} برای &quot;{2}&quot; قبلا ثبت شده است..
        /// </summary>
        public static string Logic_UserTypeUsageLayerDuplicate {
            get {
                return ResourceManager.GetString("Logic_UserTypeUsageLayerDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری {0} قبلا ثبت شده است..
        /// </summary>
        public static string Logic_UserTypeYearDuplicate {
            get {
                return ResourceManager.GetString("Logic_UserTypeYearDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات سال {0} برای &quot;{1}&quot; قبلا ثبت شده است..
        /// </summary>
        public static string Logic_YearOrgDuplicate {
            get {
                return ResourceManager.GetString("Logic_YearOrgDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل وجود داده وابسته امکان حذف نمی باشد..
        /// </summary>
        public static string RelationDataSoftDeleted {
            get {
                return ResourceManager.GetString("RelationDataSoftDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد..
        /// </summary>
        public static string Succeed {
            get {
                return ResourceManager.GetString("Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای سیستمی. لطفاً با پشتیبانی تماس بگیرید..
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
    }
}
