//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datiss.Budget.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SPTitles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPTitles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datiss.Budget.Resources.SPTitles", typeof(SPTitles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد عملیاتی آب.
        /// </summary>
        public static string IncomeCurrentOperational_Cal1 {
            get {
                return ResourceManager.GetString("IncomeCurrentOperational_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد عملیاتی فاضلاب.
        /// </summary>
        public static string IncomeCurrentOperational_Cal2 {
            get {
                return ResourceManager.GetString("IncomeCurrentOperational_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد ماده 11 آب سالیانه.
        /// </summary>
        public static string IncomeForcast_Cal1 {
            get {
                return ResourceManager.GetString("IncomeForcast_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد هزینه لوله گذاری آب سالیانه.
        /// </summary>
        public static string IncomeForcast_Cal2 {
            get {
                return ResourceManager.GetString("IncomeForcast_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد تبصره 3 ماده واحده آب سالیانه.
        /// </summary>
        public static string IncomeForcast_Cal3 {
            get {
                return ResourceManager.GetString("IncomeForcast_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد تبصره 2 ماده واحده آب سالیانه.
        /// </summary>
        public static string IncomeForcast_Cal4 {
            get {
                return ResourceManager.GetString("IncomeForcast_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد حق انشعاب آب سالیانه.
        /// </summary>
        public static string IncomeForcast_Cal5 {
            get {
                return ResourceManager.GetString("IncomeForcast_Cal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کل .
        /// </summary>
        public static string IncomeForcastOthers_Cal1 {
            get {
                return ResourceManager.GetString("IncomeForcastOthers_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد کل.
        /// </summary>
        public static string IncomeForcastOthers_Cal2 {
            get {
                return ResourceManager.GetString("IncomeForcastOthers_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد هزینه لوله گذاری سرمایه ای حجم دفع سالیانه.
        /// </summary>
        public static string IncomeForcastWs_Cal1 {
            get {
                return ResourceManager.GetString("IncomeForcastWs_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد حق انشعاب سرمایه ای حجم دفع سالیانه.
        /// </summary>
        public static string IncomeForcastWs_Cal2 {
            get {
                return ResourceManager.GetString("IncomeForcastWs_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد تبصره 3 سرمایه ای حجم دفع سالیانه.
        /// </summary>
        public static string IncomeForcastWs_Cal3 {
            get {
                return ResourceManager.GetString("IncomeForcastWs_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد ماده 11 سرمایه ای حجم دفع سالیانه.
        /// </summary>
        public static string IncomeForcastWs_Cal4 {
            get {
                return ResourceManager.GetString("IncomeForcastWs_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WasteInstallFees_Cal1.
        /// </summary>
        public static string WasteInstallFees_Cal1 {
            get {
                return ResourceManager.GetString("WasteInstallFees_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد فروش انشعاب فاضلاب سالیانه مسکونی.
        /// </summary>
        public static string WasteSalesSplit_Cal1 {
            get {
                return ResourceManager.GetString("WasteSalesSplit_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد فروش انشعاب فاضلاب سالیانه غیر مسکونی.
        /// </summary>
        public static string WasteSalesSplit_Cal2 {
            get {
                return ResourceManager.GetString("WasteSalesSplit_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد فروش انشعاب فاضلاب سالیانه مسکونی.
        /// </summary>
        public static string WasteSalesSplit_Cal3 {
            get {
                return ResourceManager.GetString("WasteSalesSplit_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد فروش انشعاب فاضلاب سالیانه غیر مسکونی.
        /// </summary>
        public static string WasteSalesSplit_Cal4 {
            get {
                return ResourceManager.GetString("WasteSalesSplit_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کل فروش انشعاب فاضلاب سالیانه.
        /// </summary>
        public static string WasteSalesSplit_Cal5 {
            get {
                return ResourceManager.GetString("WasteSalesSplit_Cal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد کل فروش انشعاب فاضلاب سالیانه.
        /// </summary>
        public static string WasteSalesSplit_Cal6 {
            get {
                return ResourceManager.GetString("WasteSalesSplit_Cal6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterInstallFees_Cal1.
        /// </summary>
        public static string WaterInstallFees_Cal1 {
            get {
                return ResourceManager.GetString("WaterInstallFees_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد فروش انشعاب آب سالیانه مسکونی.
        /// </summary>
        public static string WaterSalesSplit_Cal1 {
            get {
                return ResourceManager.GetString("WaterSalesSplit_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد فروش انشعاب آب سالیانه غیر مسکونی.
        /// </summary>
        public static string WaterSalesSplit_Cal2 {
            get {
                return ResourceManager.GetString("WaterSalesSplit_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد فروش انشعاب آب سالیانه مسکونی.
        /// </summary>
        public static string WaterSalesSplit_Cal3 {
            get {
                return ResourceManager.GetString("WaterSalesSplit_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد فروش انشعاب آب سالیانه غیر مسکونی.
        /// </summary>
        public static string WaterSalesSplit_Cal4 {
            get {
                return ResourceManager.GetString("WaterSalesSplit_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کل فروش انشعاب آب سالیانه.
        /// </summary>
        public static string WaterSalesSplit_Cal5 {
            get {
                return ResourceManager.GetString("WaterSalesSplit_Cal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد کل فروش انشعاب آب سالیانه.
        /// </summary>
        public static string WaterSalesSplit_Cal6 {
            get {
                return ResourceManager.GetString("WaterSalesSplit_Cal6", resourceCulture);
            }
        }
    }
}
