//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datiss.Budget.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SPTitles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPTitles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datiss.Budget.Resources.SPTitles", typeof(SPTitles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توزیع تعدادی مصرف آب سالیانه مسکونی.
        /// </summary>
        public static string ConsumeForcast_Cal1 {
            get {
                return ResourceManager.GetString("ConsumeForcast_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توزیع تعدادی مصرف آب سالیانه غیر مسکونی.
        /// </summary>
        public static string ConsumeForcast_Cal2 {
            get {
                return ResourceManager.GetString("ConsumeForcast_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توزیع آحادی مصرف آب سالیانه مسکونی.
        /// </summary>
        public static string ConsumeForcast_Cal3 {
            get {
                return ResourceManager.GetString("ConsumeForcast_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توزیع آحادی مصرف آب سالیانه غیر مسکونی.
        /// </summary>
        public static string ConsumeForcast_Cal4 {
            get {
                return ResourceManager.GetString("ConsumeForcast_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توزیع تعدادی حجم دفع سالیانه مسکونی.
        /// </summary>
        public static string ConsumeForcastWs_Cal1 {
            get {
                return ResourceManager.GetString("ConsumeForcastWs_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توزیع تعدادی حجم دفع سالیانه غیر مسکونی.
        /// </summary>
        public static string ConsumeForcastWs_Cal2 {
            get {
                return ResourceManager.GetString("ConsumeForcastWs_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توزیع آحادی حجم دفع سالیانه مسکونی.
        /// </summary>
        public static string ConsumeForcastWs_Cal3 {
            get {
                return ResourceManager.GetString("ConsumeForcastWs_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توزیع آحادی حجم دفع سالیانه غیر مسکونی.
        /// </summary>
        public static string ConsumeForcastWs_Cal4 {
            get {
                return ResourceManager.GetString("ConsumeForcastWs_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع ماده مصرفی.
        /// </summary>
        public static string CostCurrentConsumable_Cal1 {
            get {
                return ResourceManager.GetString("CostCurrentConsumable_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع مبلغ.
        /// </summary>
        public static string CostCurrentConsumable_Cal2 {
            get {
                return ResourceManager.GetString("CostCurrentConsumable_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع هزینه برق مصرفی (کیلووات ساعت).
        /// </summary>
        public static string CostCurrentElectricity_Cal1 {
            get {
                return ResourceManager.GetString("CostCurrentElectricity_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع قیمت برق مصرفی (میلیون ریال).
        /// </summary>
        public static string CostCurrentElectricity_Cal2 {
            get {
                return ResourceManager.GetString("CostCurrentElectricity_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد آب بها مشترکین مسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWH_Cal1 {
            get {
                return ResourceManager.GetString("IncomeCurrentWH_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد آبونمان مشترکین مسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWH_Cal2 {
            get {
                return ResourceManager.GetString("IncomeCurrentWH_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد فصلی مشترکین مسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWH_Cal3 {
            get {
                return ResourceManager.GetString("IncomeCurrentWH_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد تبصره 2 مشترکین مسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWH_Cal4 {
            get {
                return ResourceManager.GetString("IncomeCurrentWH_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد تبصره 3 مشترکین مسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWH_Cal5 {
            get {
                return ResourceManager.GetString("IncomeCurrentWH_Cal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد کل مشترکین مسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWH_Cal6 {
            get {
                return ResourceManager.GetString("IncomeCurrentWH_Cal6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع آحاد مشترکین مسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWH_Cal7 {
            get {
                return ResourceManager.GetString("IncomeCurrentWH_Cal7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع تعداد مشترکین مسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWH_Cal8 {
            get {
                return ResourceManager.GetString("IncomeCurrentWH_Cal8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع مصرف مشترکین مسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWH_Cal9 {
            get {
                return ResourceManager.GetString("IncomeCurrentWH_Cal9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد آب بها مشترکین غیرمسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWNH_Cal1 {
            get {
                return ResourceManager.GetString("IncomeCurrentWNH_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع مصرف مشترکین غیرمسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWNH_Cal10 {
            get {
                return ResourceManager.GetString("IncomeCurrentWNH_Cal10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد مازاد بر ظرفیت آب بها مشترکین غیرمسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWNH_Cal2 {
            get {
                return ResourceManager.GetString("IncomeCurrentWNH_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد فصلی آب بها مشترکین غیرمسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWNH_Cal3 {
            get {
                return ResourceManager.GetString("IncomeCurrentWNH_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد تبصره 2 آب بها مشترکین غیرمسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWNH_Cal4 {
            get {
                return ResourceManager.GetString("IncomeCurrentWNH_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد تبصره 3 آب بها مشترکین غیرمسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWNH_Cal5 {
            get {
                return ResourceManager.GetString("IncomeCurrentWNH_Cal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد آبونمان آب بها مشترکین غیرمسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWNH_Cal6 {
            get {
                return ResourceManager.GetString("IncomeCurrentWNH_Cal6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد آب بها کل مشترکین غیرمسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWNH_Cal7 {
            get {
                return ResourceManager.GetString("IncomeCurrentWNH_Cal7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع تعداد مشترکین غیرمسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWNH_Cal8 {
            get {
                return ResourceManager.GetString("IncomeCurrentWNH_Cal8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع آحاد مشترکین غیرمسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWNH_Cal9 {
            get {
                return ResourceManager.GetString("IncomeCurrentWNH_Cal9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد کارمزد دفع مشترکین مسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWsH_Cal1 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsH_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد فصلی کارمزد دفع مشترکین مسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWsH_Cal2 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsH_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع آبونمان کارمزد دفع مشترکین مسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWsH_Cal3 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsH_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد تبصره3 کارمزد دفع مشترکین مسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWsH_Cal4 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsH_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد کل کارمزد دفع مشترکین مسکونی سالیانه.
        /// </summary>
        public static string IncomeCurrentWsH_Cal5 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsH_Cal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع تعداد مشترکین فاضلاب سالیانه.
        /// </summary>
        public static string IncomeCurrentWsH_Cal6 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsH_Cal6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع آحاد مشترکین فاضلاب سالیانه.
        /// </summary>
        public static string IncomeCurrentWsH_Cal7 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsH_Cal7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع حجم دفع فاضلاب سالیانه.
        /// </summary>
        public static string IncomeCurrentWsH_Cal8 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsH_Cal8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد خدمات دفع فاضلاب مشترکین غیر مسکونی.
        /// </summary>
        public static string IncomeCurrentWsNH_Cal1 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsNH_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد مازاد بر ظرفیت خدمات دفع فاضلاب مشترکین غیر مسکونی.
        /// </summary>
        public static string IncomeCurrentWsNH_Cal2 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsNH_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد فصلی خدمات دفع فاضلاب مشترکین غیر مسکونی.
        /// </summary>
        public static string IncomeCurrentWsNH_Cal3 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsNH_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد تبصره 3 خدمات دفع فاضلاب مشترکین غیر مسکونی.
        /// </summary>
        public static string IncomeCurrentWsNH_Cal4 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsNH_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد کل خدمات دفع فاضلاب مشترکین غیر مسکونی.
        /// </summary>
        public static string IncomeCurrentWsNH_Cal5 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsNH_Cal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع درآمد آبونمان خدمات دفع فاضلاب مشترکین غیر مسکونی.
        /// </summary>
        public static string IncomeCurrentWsNH_Cal6 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsNH_Cal6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع تعداد مشترکین فاضلاب غیر مسکونی.
        /// </summary>
        public static string IncomeCurrentWsNH_Cal7 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsNH_Cal7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع آحاد مشترکین فاضلاب غیر مسکونی.
        /// </summary>
        public static string IncomeCurrentWsNH_Cal8 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsNH_Cal8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع حجم دفع فاضلاب غیر مسکونی.
        /// </summary>
        public static string IncomeCurrentWsNH_Cal9 {
            get {
                return ResourceManager.GetString("IncomeCurrentWsNH_Cal9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد ماده 11 آب سالیانه.
        /// </summary>
        public static string IncomeForcast_Cal1 {
            get {
                return ResourceManager.GetString("IncomeForcast_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد هزینه لوله گذاری آب سالیانه.
        /// </summary>
        public static string IncomeForcast_Cal2 {
            get {
                return ResourceManager.GetString("IncomeForcast_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد تبصره 3 ماده واحده آب سالیانه.
        /// </summary>
        public static string IncomeForcast_Cal3 {
            get {
                return ResourceManager.GetString("IncomeForcast_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد تبصره 2 ماده واحده آب سالیانه.
        /// </summary>
        public static string IncomeForcast_Cal4 {
            get {
                return ResourceManager.GetString("IncomeForcast_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد حق انشعاب آب سالیانه.
        /// </summary>
        public static string IncomeForcast_Cal5 {
            get {
                return ResourceManager.GetString("IncomeForcast_Cal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کل .
        /// </summary>
        public static string IncomeForcastOthers_Cal1 {
            get {
                return ResourceManager.GetString("IncomeForcastOthers_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد کل.
        /// </summary>
        public static string IncomeForcastOthers_Cal2 {
            get {
                return ResourceManager.GetString("IncomeForcastOthers_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد هزینه لوله گذاری سرمایه ای حجم دفع سالیانه.
        /// </summary>
        public static string IncomeForcastWs_Cal1 {
            get {
                return ResourceManager.GetString("IncomeForcastWs_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد حق انشعاب سرمایه ای حجم دفع سالیانه.
        /// </summary>
        public static string IncomeForcastWs_Cal2 {
            get {
                return ResourceManager.GetString("IncomeForcastWs_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد تبصره 3 سرمایه ای حجم دفع سالیانه.
        /// </summary>
        public static string IncomeForcastWs_Cal3 {
            get {
                return ResourceManager.GetString("IncomeForcastWs_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد ماده 11 سرمایه ای حجم دفع سالیانه.
        /// </summary>
        public static string IncomeForcastWs_Cal4 {
            get {
                return ResourceManager.GetString("IncomeForcastWs_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد انشعاب آب پایان شش ماهه اول سال ماقبل.
        /// </summary>
        public static string SalesSplitTotal_Cal1 {
            get {
                return ResourceManager.GetString("SalesSplitTotal_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد انشعاب آب پایان شش ماهه اول سال ماقبل.
        /// </summary>
        public static string SalesSplitTotal_Cal2 {
            get {
                return ResourceManager.GetString("SalesSplitTotal_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد انشعاب آب شش ماهه دوم سال ماقبل.
        /// </summary>
        public static string SalesSplitTotal_Cal3 {
            get {
                return ResourceManager.GetString("SalesSplitTotal_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد انشعاب آب شش ماهه دوم سال ماقبل.
        /// </summary>
        public static string SalesSplitTotal_Cal4 {
            get {
                return ResourceManager.GetString("SalesSplitTotal_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد انشعاب فاضلاب پایان شش ماهه اول سال ماقبل.
        /// </summary>
        public static string SalesSplitTotal_Cal5 {
            get {
                return ResourceManager.GetString("SalesSplitTotal_Cal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد انشعاب فاضلاب پایان شش ماهه اول سال ماقبل.
        /// </summary>
        public static string SalesSplitTotal_Cal6 {
            get {
                return ResourceManager.GetString("SalesSplitTotal_Cal6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد انشعاب فاضلاب شش ماهه دوم سال ماقبل.
        /// </summary>
        public static string SalesSplitTotal_Cal7 {
            get {
                return ResourceManager.GetString("SalesSplitTotal_Cal7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد انشعاب فاضلاب شش ماهه دوم سال ماقبل.
        /// </summary>
        public static string SalesSplitTotal_Cal8 {
            get {
                return ResourceManager.GetString("SalesSplitTotal_Cal8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WasteInstallFees_Cal1.
        /// </summary>
        public static string WasteInstallFees_Cal1 {
            get {
                return ResourceManager.GetString("WasteInstallFees_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد فروش انشعاب فاضلاب سالیانه مسکونی.
        /// </summary>
        public static string WasteSalesSplit_Cal1 {
            get {
                return ResourceManager.GetString("WasteSalesSplit_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد فروش انشعاب فاضلاب سالیانه غیر مسکونی.
        /// </summary>
        public static string WasteSalesSplit_Cal2 {
            get {
                return ResourceManager.GetString("WasteSalesSplit_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد فروش انشعاب فاضلاب سالیانه مسکونی.
        /// </summary>
        public static string WasteSalesSplit_Cal3 {
            get {
                return ResourceManager.GetString("WasteSalesSplit_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد فروش انشعاب فاضلاب سالیانه غیر مسکونی.
        /// </summary>
        public static string WasteSalesSplit_Cal4 {
            get {
                return ResourceManager.GetString("WasteSalesSplit_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کل فروش انشعاب فاضلاب سالیانه.
        /// </summary>
        public static string WasteSalesSplit_Cal5 {
            get {
                return ResourceManager.GetString("WasteSalesSplit_Cal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد کل فروش انشعاب فاضلاب سالیانه.
        /// </summary>
        public static string WasteSalesSplit_Cal6 {
            get {
                return ResourceManager.GetString("WasteSalesSplit_Cal6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterInstallFees_Cal1.
        /// </summary>
        public static string WaterInstallFees_Cal1 {
            get {
                return ResourceManager.GetString("WaterInstallFees_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد فروش انشعاب آب سالیانه مسکونی.
        /// </summary>
        public static string WaterSalesSplit_Cal1 {
            get {
                return ResourceManager.GetString("WaterSalesSplit_Cal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد فروش انشعاب آب سالیانه غیر مسکونی.
        /// </summary>
        public static string WaterSalesSplit_Cal2 {
            get {
                return ResourceManager.GetString("WaterSalesSplit_Cal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد فروش انشعاب آب سالیانه مسکونی.
        /// </summary>
        public static string WaterSalesSplit_Cal3 {
            get {
                return ResourceManager.GetString("WaterSalesSplit_Cal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد فروش انشعاب آب سالیانه غیر مسکونی.
        /// </summary>
        public static string WaterSalesSplit_Cal4 {
            get {
                return ResourceManager.GetString("WaterSalesSplit_Cal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کل فروش انشعاب آب سالیانه.
        /// </summary>
        public static string WaterSalesSplit_Cal5 {
            get {
                return ResourceManager.GetString("WaterSalesSplit_Cal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آحاد کل فروش انشعاب آب سالیانه.
        /// </summary>
        public static string WaterSalesSplit_Cal6 {
            get {
                return ResourceManager.GetString("WaterSalesSplit_Cal6", resourceCulture);
            }
        }
    }
}
