//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datiss.Budget.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datiss.Budget.Resources.ViewMessages", typeof(ViewMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال هدف نباید دیتا داشته باشد.
        /// </summary>
        public static string CopyDestYearHasData {
            get {
                return ResourceManager.GetString("CopyDestYearHasData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال ها یکی نباشد.
        /// </summary>
        public static string CopySameYear {
            get {
                return ResourceManager.GetString("CopySameYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان مورد نظر برای سال مبدا داده ای ندارد ..
        /// </summary>
        public static string CopySourceOrgNullData {
            get {
                return ResourceManager.GetString("CopySourceOrgNullData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کپی اطلاعات با موفقیت انجام شد.
        /// </summary>
        public static string CopySuccess {
            get {
                return ResourceManager.GetString("CopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف رکورد برای سازمان {0} در سال {1} با موفقیت انجام شد..
        /// </summary>
        public static string DeleteMultipleDataForOrg {
            get {
                return ResourceManager.GetString("DeleteMultipleDataForOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدلیل وجود داده های وابسته امکان حذف رکورد وجود ندارد..
        /// </summary>
        public static string DeleteRelatedData {
            get {
                return ResourceManager.GetString("DeleteRelatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت فایل اکسل نمی باشد..
        /// </summary>
        public static string ImportExcelFileFormatInvalid {
            get {
                return ResourceManager.GetString("ImportExcelFileFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد سطر {0} از قبل وجود دارد.
        /// </summary>
        public static string ImportExcelFileItemExist {
            get {
                return ResourceManager.GetString("ImportExcelFileItemExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز فایل بیش از حد مجاز است..
        /// </summary>
        public static string ImportExcelFileSizeInvalid {
            get {
                return ResourceManager.GetString("ImportExcelFileSizeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ورود فایل اکسل با موفقیت انجام گردید.
        /// </summary>
        public static string ImportExcelSuccess {
            get {
                return ResourceManager.GetString("ImportExcelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و یا کلمه‌ی عبور وارد شده معتبر نیستند.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجازه ورود به سیستم برای شما وجود ندارد..
        /// </summary>
        public static string LoginNotAllowed {
            get {
                return ResourceManager.GetString("LoginNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً داده های ورودی خود را چک کنید..
        /// </summary>
        public static string ModelState {
            get {
                return ResourceManager.GetString("ModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مورد نظر یافت نشد..
        /// </summary>
        public static string NullRef {
            get {
                return ResourceManager.GetString("NullRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای سیستمی. لطفاً با پشتیبانی تماس بگیرید..
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما غیرفعال شده‌است..
        /// </summary>
        public static string UserDisabled {
            get {
                return ResourceManager.GetString("UserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا به پست الکترونیک خود مراجعه کرده و ایمیل خود را تائید کنید!.
        /// </summary>
        public static string UserEmailNotConfirmed {
            get {
                return ResourceManager.GetString("UserEmailNotConfirmed", resourceCulture);
            }
        }
    }
}
